@startuml

actor User
participant Duke
participant Ui
participant Storage
participant TransactionManager
participant Parser

== List Transactions ==
User -> Duke : Enter "list" command
activate Duke
Duke -> Ui : readCommand()
activate Ui
Ui -> User : Prompt for input
deactivate Ui
Duke -> Parser : parser(command)
activate Parser
Parser -> TransactionManager : getTransactions()
activate TransactionManager
TransactionManager -> Ui : printTransactions(transactions)
deactivate TransactionManager
Ui -> User : Display list of transactions
deactivate Ui
deactivate Duke

@enduml
