@startuml

actor User
participant Duke
participant Ui
participant Storage
participant TransactionManager
participant Parser

== Untick Transaction ==
User -> Duke : Enter "untick" command
activate Duke
Duke -> Ui : readCommand()
activate Ui
Ui -> User : Prompt for input
deactivate Ui
User -> Ui : Enter transaction details
Duke -> Parser : parser(command)
activate Parser
Parser -> TransactionManager : unTickTransaction(id)
activate TransactionManager
TransactionManager -> Ui : unTickTransaction(transaction)
deactivate TransactionManager
Ui -> User : Display unticked transaction
deactivate Ui
deactivate Duke

@enduml
